version: '3'
services:

  api:
    container_name: api-album-dock
    restart: always
    build: .
    ports:
      - 5019:8080
    links:
      - mongo
  mongo:
    container_name: mongoDB
    image: mongo
    ports:
      - 27022:27017
